name: nlpc
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.6
  - pip=20.2.4
  - torchvision
  - pytorch=1.7.0
  - torchtext
  - cudatoolkit=11.0
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - flake8
  - pyyaml
  - tensorboard
  - pip:
    - filelock==3.0.12
    - protobuf==3.14.0
    - regex==2020.11.13
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - tensorboardx==2.1
    - tokenizers==0.9.3
    - transformers==3.5.1
    - emojiswitch==0.0.1
